### ISSUE TITLE
/muteall and /unmuteall commands

### ISSUE THREAD

**Issue by cafestifflered** [cafestifflered/ChatRestrict#3]
Rather than connecting the /muteall and /unmuteall commands to the rules as aliases for the rule enable/disable toggle, simply disable all chat. Do not modify the `enabled:` param on any rules.

Some variations and permissions:
- `/muteall` - chatrestrict.muteall (includes tempmuteall)
- `/unmuteall` - chatrestrict.unmuteall
- `/tempmuteall <1d7h>` - chatrestrict.tempmuteall (does not include muteall)

**Comment by Owen1212055** [comment]
I've moved /tempmuteall off for a little bit.
