### ISSUE TITLE
disable and enable commands cleanup

### ISSUE THREAD

**Issue by cafestifflered** [cafestifflered/ChatRestrict#9]
_EDIT: This initial comment is wrong, but I'm keeping it here so you can follow my thought process._

When running `/chatrestrict enable <rulename>` there's duplicate text in the first two lines

<img width="456" alt="Screen Shot 2022-06-12 at 3 09 49 AM" src="https://user-images.githubusercontent.com/73274299/173221748-6dd7f99d-3d26-42a5-b971-ea133cb0b960.png">

When running `/chatrestrict disable <rulename>` the same text above shows once (we don't need to show it at all, since this command is disabling the rules) and the rule is hidden. The rule should be displayed so the admin can see what they just disabled.

<img width="442" alt="Screen Shot 2022-06-12 at 3 11 16 AM" src="https://user-images.githubusercontent.com/73274299/173221785-b99c8ac2-9651-426c-87cd-48f55248ef32.png">

**Comment by cafestifflered** [comment]
I see now what you did here. When the disable/enable commands are run, you are listing all of the rules that are enabled and disabled. The rules that are disabled are listed as hidden.

Instead, only show the description of the rule that was enabled or disabled. Don't show the list of all rules.

**Comment by cafestifflered** [comment]
We can create a new command later (not at all needed right now), something like `/chatrestrict rules` (with a permission) which lists all of the enabled rules and shows the count for hidden (disabled) rules.

**Comment by cafestifflered** [comment]
I also see now why the line "All of the following conditions must return " showed twice. The ruleset has its own message that needs to be shown for the rules contained within it.

If you follow what I described as the solution above by not listing ALL of the rules after one is disabled/enabled, then we can save this, "All of the following conditions..." message to display when enabling/disabling a ruleset.

Let me give an example in case I've spoken unclearly:
There are two rules. One is a ruleset with two rules.
```
rules:
  cool-rule:
    type: "allowed_weekdays"
    weekdays: ["MONDAY"]
  cool-ruleset:
    type: "ruleset"
    cool-rule-two:
      [params]
    cool-rule-three:
      [params]
```
If I run the command `/chatrestrict disable cool-rule`, I see a message in chat:
- "You have disabled cool-rule. Description: Blah blah description"

If I run the command `/chatrestrict enable cool-ruleset`, I see a different message in chat:
- "You have disabled cool-ruleset. Description: All of the following conditions must return true: Blah blah description of rules in set"

**Comment by Owen1212055** [comment]
Yeah, it will now only show the command you enabled/disabled.
